# Generated by Django 4.2.18 on 2025-01-18 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Accion', 'Accion'), ('Ciencia Ficcion', 'Ciencia Ficcion'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Romantica', 'Romantica'), ('Comedia', 'Comedia')])),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Arriendo', 'Arriendo')])),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada')])),
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
