# Generated by Django 4.2.18 on 2025-01-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Accion', 'Accion'), ('Ciencia Ficcion', 'Ciencia Ficcion'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Romantica', 'Romantica'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Crimen', 'Crimen'), ('Animacion', 'Animacion')]),
        ),
    ]
