# Generated by Django 4.2.18 on 2025-01-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_pelicula_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
