# Generated by Django 4.2.18 on 2025-01-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
    ]
