# Generated by Django 4.2.18 on 2025-01-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_pelicula_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='precio_arriendo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
